language: python

dist: xenial

notifications:
    on_success: change
    on_failure: always

matrix:
    include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=py27 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5432/test" POSTGRESQL=1
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5432/test" POSTGRESQL=1
      addons:
        postgresql: "9.4"
    - python: 3.6
      env: TOXENV=py36 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5432/test" POSTGRESQL=1
      addons:
        postgresql: "9.6"
    - python: 3.6
      env: TOXENV=py36 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5433/test" POSTGRESQL=1
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
    - python: 3.6
      env: TOXENV=py36 BCRYPT="enabled" DB_STRING="mysql+mysqlconnector://travis@localhost/test" MYSQL=1
    - python: 3.6
      env: TOXENV=py36 BCRYPT="enabled" DB_STRING="mysql+mysqldb://travis@localhost/test" MYSQL=1
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=lint
    - python: nightly
      env: TOXENV=py37
    allow_failures:
    - python: nightly

install:
- travis_retry pip install -U setuptools pip tox

script:
- travis_retry tox

services:
- postgresql
- mysql



before_script:
  - if [ -n "$POSTGRESQL" ]; then psql -c 'create database test;' -U postgres; fi
  - if [ -n "$MYSQL" ]; then mysql -e 'create database test;'; fi

after_success:
  - pip install coveralls
  - coveralls
