language: python

dist: xenial

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=py27 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5432/test" DB=postgres
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5432/test" DB=postgres
    addons:
      postgresql: "9.4"
  - python: 3.6
    env: TOXENV=py36 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5432/test" DB=postgres
    addons:
      postgresql: "9.6"
  - python: 3.6
    env: TOXENV=py36 BCRYPT="enabled" DB_STRING="postgres://postgres@127.0.0.1:5432/test" DB=postgres PGPORT=5432
    addons:
      postgresql: "10"
      apt:
        packages:
        - postgresql-10
        - postgresql-client-10
  - python: 3.6
    env: TOXENV=py36 BCRYPT="enabled" DB_STRING="mysql+mysqlconnector://travis@localhost/test" DB=mysql
  - python: 3.6
    env: TOXENV=py36 BCRYPT="enabled" DB_STRING="mysql+mysqldb://travis@localhost/test" DB=mysql
    addons:
      mysql: "5.7"
  - python: 3.6
    env: TOXENV=py36 BCRYPT="enabled" DB_STRING="mysql+mysqldb://root@localhost/test" DB=mysql
    before_install:
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/repo-codename select xenial'
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/repo-distro select ubuntu'
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/repo-url string http://repo.mysql.com/apt/'
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/select-preview select '
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/select-product select Ok'
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/select-server select mysql-8.0'
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/select-tools select '
    - sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/unsupported-platform select abort'
    - wget https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
    - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
    - sudo apt update
    - sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/root-pass password "
    - sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/re-root-pass password "
    - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server
    - sudo systemctl start mysql
    - sudo mysql_upgrade
  - python: 3.6
    env: TOXENV=py36 BCRYPT="enabled" DB_STRING="mysql+mysqldb://travis@localhost/test" DB=mysql
    addons:
      mariadb: "10.3"
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=lint
  - python: nightly
    env: TOXENV=py37
  allow_failures:
  - python: nightly

install:
- travis_retry pip install -U setuptools pip tox

script:
- travis_retry tox

services:
- postgresql
- mysql



before_script:
- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database test;' -U postgres; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database test;'; fi"

after_success:
- pip install coveralls
- coveralls
